### ISSUE TITLE
Data Browser 3 Drag/Drop

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#228]
The Data Browser plot accepts dropped PV names or archive data sources.
This was originally done via SWT drag/drop.
Now the plot is JavaFX, hosted by an FXCanvas.
The FXCanvas already initializes drag/drop to forward between SWT and JavaFX.
It's not possible to add a second drop target, so `fixCanvasDragAndDrop()` was added to remove the first FXCanvas drop target and add ours.

This worked on Mac and Linux, but fails on Windows:
```
org.eclipse.swt.SWTError: Cannot initialize Drop
        at org.eclipse.swt.dnd.DND.error(DND.java:277)
        at org.eclipse.swt.dnd.DND.error(DND.java:238)
        at org.eclipse.swt.dnd.DropTarget.<init>(DropTarget.java:144)
        at org.csstudio.ui.util.dnd.ControlSystemDropTarget.<init>(ControlSystemDropTarget.java:45)
        at org.csstudio.trends.databrowser3.editor.DataBrowserEditor$4.<init>(DataBrowserEditor.java:398)
        at org.csstudio.trends.databrowser3.editor.DataBrowserEditor.fixCanvasDragAndDrop(DataBrowserEditor.java:398)
        at org.csstudio.trends.databrowser3.editor.DataBrowserEditor.createPartControl(DataBrowserEditor.java:326)
```

**Comment by kasemir** [comment]
Idea to fix this: Remove `fixCanvasDragAndDrop`, don't adjust the FXCanvas, but use a JavaFX drop target on the underlying JFX plot.

**Comment by kasemir** [comment]
org.csstudio.ui.util.dnd.ControlSystem[Drag/Drop] introduces custom transfer types.

A plain JavaFX drop test will see when for example a [java:org.csstudio.csdata.ProcessVariable] is dragged in from an archive search view in a separate CS-Studio process, and it might be possible to de-serialize it.

But when that same JavaFX drop test runs inside an FXCanvas, it only receives [text/plain] as a mime type.

**Comment by kasemir** [comment]
Related:
 * https://bugs.eclipse.org/bugs/show_bug.cgi?id=162192 , cannot remove an SWT drop target
 * https://www.reddit.com/r/javahelp/comments/2feh7y/dnd_using_custom_drag_types_into_an_fxcanvas_java , FXCanvas does not forward custom data types
 * http://book2s.com/java/src/package/javafx/embed/swt/fxcanvas.html, one version of the FXCanvas source code
