### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#351]
@kasemir I'm asking your help because I tried to figure out the cause of this exception but I've not found why it happens and how to solve it.

```
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
	at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:386)
	at java.util.AbstractList$Itr.next(AbstractList.java:355)
	at java.util.SubList$1.next(AbstractList.java:707)
	at javafx.scene.control.ContextMenu$2.onChanged(ContextMenu.java:184)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$29(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at org.csstudio.display.builder.representation.javafx.AutocompleteMenu.lambda$2(AutocompleteMenu.java:279)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5084)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5465)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.csstudio.utility.product.Workbench.runWorkbench(Workbench.java:99)
	at org.csstudio.startup.application.Application.startApplication(Application.java:265)
	at org.csstudio.startup.application.Application.start(Application.java:119)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

Having a reproducible situation is difficult but the colleague that raised the problem was able to set up it. The problem happens when editing a PV name. Here how to reproduce the problem.

Attached there is a workspace with the necessary bob files:

[ESS-CS-Studio.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1728874/ESS-CS-Studio.zip)

Don't try to copy the files in your existent workspace: when I did it I was unable to reproduce the problem.

1. Start CS-Studio from a console and switch to the provided workspace
2. Select the text-update shown on the attached picture
3. Click on the pv_name property
4. Press HOME and start typing
5. There should be at least one ConcurrentModificationException

![concurrentmodificationexception](https://user-images.githubusercontent.com/10833922/36273911-55fd31c6-1286-11e8-9f67-21e353427280.png)

**Comment by claudio-rosati** [comment]
Thank you Kay.
I'll give the new version to my colleague asking him to test more, then I'll close the issue.

**Comment by claudio-rosati** [comment]
Tested and working.
