### ISSUE TITLE
SyntaxHighlightedMultiLineInputDialog won't open

### ISSUE THREAD

**Issue by kasemir** [kasemir/org.csstudio.display.builder#379]
See https://github.com/ControlSystemStudio/org.csstudio.product/pull/42:

Recent changes to use Eclipse 4.7 and prepare for Java 9 break the SyntaxHighlightedMultiLineInputDialog at runtime. 

When I open the syntax-highlighting script editor in the display builder, either via "Show Script" in the rules dialog or via "Edit" for an embedded script in the script dialog, this results in
```
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: org.fxmisc.undo.UndoManagerFactory.create(Lorg/reactfx/EventStream;Ljava/util/function/Function;Ljava/util/function/Consumer;Ljava/util/function/BiFunction;Ljava/util/function/Predicate;Ljava/time/Duration;)Lorg/fxmisc/undo/UndoManager;
	at org.fxmisc.richtext.util.UndoUtils.plainTextUndoManager(UndoUtils.java:123)
..
	at org.fxmisc.richtext.CodeArea.<init>(CodeArea.java:36)
	at org.csstudio.javafx.SyntaxHighlightedMultiLineInputDialog.<init>(SyntaxHighlightedMultiLineInputDialog.java:57)
```

**Comment by kasemir** [comment]
@claudio-rosati  I left the dependencies on `richtext` etc. untouched, only replaced calls to `SyntaxHighlightedMultiLineInputDialog` with `MultiLineInputDialog` because I need a product where the script text can be seen and edited.

Not sure if it's easier to figure out how to re-enable the `SyntaxHighlightedMultiLineInputDialog` via updates of the libraries for Java 8, as you started on https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/65, or first move to Java 9 and then see how a `SyntaxHighlightedMultiLineInputDialog` could be implemented.

**Comment by claudio-rosati** [comment]
@kasemir 
I've just updated the pull request [maven-osgi-bundle#65](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/65) resolving the conflict.
If you want you can try and see if this solve the problem, otherwise I'll do it later next week.

**Comment by claudio-rosati** [comment]
@kasemir 
This is now solved. Should we close the issue?
